//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfpLauncher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>BOI 4.8|@boi4.8</string>
  <string>Yugo|@xrofp</string>
  <string>BW|@80+Islands1.3;@res-z;@BW@DVD1.79</string>
  <string>TZK 4.0.3|@TZK_4.0.0;@TZK_4.0.3;@TZK_Islands;@80+Islands1.3</string>
  <string>TZK 4.0.6|@TZK_4.0.0;@TZK_4.0.3;@TZK_4.0.4;@TZK_4.0.5;@TZK_4.0.6;@TZK_Islands;@TZK_Islands_v2;@80+Islands1.3</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Mods {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Mods"]));
            }
            set {
                this["Mods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BaseParameters {
            get {
                return ((string)(this["BaseParameters"]));
            }
            set {
                this["BaseParameters"] = value;
            }
        }
    }
}
